import type { Metadata } from "next";
import { Archivo } from "next/font/google";
import "./globals.css";
import { cn } from "@/lib/utils";

const archivo = Archivo({ 
  subsets: ["latin"],
  weight: ["200", "300", "400", "500", "600", "700", "800", "900"],
  variable: '--font-archivo'
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className={cn("h-full", "antialiased", archivo.variable)}
    >
      <body 
        className={`${archivo.variable} antialiased selection:bg-zinc-950 selection:text-zinc-200 bg-zinc-100`}
      >
        {children}
      </body>
    </html>
  );
}
